spring:
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          client-id: '{cipher}37120218ad80c5be60f695f729a0647e988c35d9f50515bbc69308ab50b9f619'
          client-secret: '{cipher}37120218ad80c5be60f695f729a0647e988c35d9f50515bbc69308ab50b9f619'
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: http://localhost:3001
            allowedMethods: '*'
            allowedHeaders: '*'
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
