spring:
  application:
    name: setting-service
  profiles:
    active: native, git
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configs
        git:
          uri: ${GIT_URL:https://github.com/Fort163/setting-service.git}
          default-label: master
          username: ${GIT_USER}
          password: ${GIT_PASSWORD}
          search-paths:
            - company
            - part-time
            - auth
            - qr-b2b
            - eureka
            - gateway
            - notification
server:
  port: 8001
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - env
          - info
          - liquibase
          - refresh
  endpoint:
    env:
      show-values: ${ACTUATOR_ENV_VALUES:ALWAYS}
encrypt:
  key: ${ENCRYPT_KEY}

