spring:
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          client-id: '{cipher}3cc31b3b89ae303e26b9a0b5f5511e1825bfcbde33e9f98ad4d7fbb3157a37f9'
          client-secret: '{cipher}3cc31b3b89ae303e26b9a0b5f5511e1825bfcbde33e9f98ad4d7fbb3157a37f9'
  datasource:
    url: jdbc:postgresql://127.0.0.1:5497/company
    username: '{cipher}6a22015c97a80498e4643aa7629d301c6b96d80e0176cfa31b8138fceb383e8e'
    password: '{cipher}5f1b30e8dc26c8d723434f7814606f8d8eee9e1a5239100c73897f9d631ad615'
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092,localhost:9093
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
qr-cache:
  enabled: true
  redis:
    server:
      host: localhost
      port: 6397
      user: '{cipher}24aef6f69eed41f2fed19d76da20e0865bd9164f88d15748368c8f55c0d7d63b'
      password: '{cipher}79ac1fcb66ce1e7725f383b6b6d3e5907b12bbc68094b2618ae0ee8585eefedd'
