spring:
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          client-id: '{cipher}ac5c602b7ee9e2e69ce226290be0fb1b73517876b190cb463f48faf3964b463b'
          client-secret: '{cipher}ac5c602b7ee9e2e69ce226290be0fb1b73517876b190cb463f48faf3964b463b'
  datasource:
    url: jdbc:postgresql://company-infrastructure-postgres-1:5497/company
    username: '{cipher}dd1fba81a89fe70699c875ad7a1ae690474a0b620d525cc05d1764ad5503e3aa'
    password: '{cipher}2979b3095b91fb95631b27a9b0567d257eb95978ba795b01982985b5a49c485e'
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092,localhost:9093
eureka:
  instance:
    hostname: eureka
  client:
    service-url:
      defaultZone: http://single-service-eureka-1:8761/eureka
